### ISSUE TITLE
vm_docker function name

### ISSUE THREAD

**Issue by frontsidebus** [0x4447/0x4447_docker#6]
Should this function be called "vm_docker" ? It's a little confusing since we aren't actually working with a virtual machine?

doesn't affect functionality, I might be nitpicking here... 

`vm_docker(){
    docker run -it -h docker --mount src=/Users/davidgatti/Documents/GitHub,target="/home/$USER/workdir/",type=bind 0x4447:latest
}`

**Comment by davidgatti** [comment]
Hello there :) since this Dockerfile replaces the VM that I was using, I'm calling it VM as reminder what the purpose is or was. In my mind VM here is just a thing that is separated from the main OS, where I can kill crash and destroy, and then start over.

My own personal legacy stuff :) I hope it makes sense, probably it won't, because I'm just human  🤪
